import { DEPARTMENT_PERMISSIONS } from "./permissions.constants.js";

export const DEPARTMENT_ROLES = {
    HOD: [
        DEPARTMENT_PERMISSIONS.MANAGE_DEPARTMENT,
        DEPARTMENT_PERMISSIONS.MANAGE_STUDENTS,
        DEPARTMENT_PERMISSIONS.MANAGE_FACULTY,
        DEPARTMENT_PERMISSIONS.MANAGE_COURSES,
        DEPARTMENT_PERMISSIONS.VIEW_REPORTS
    ],

    HOD_ASSISTANT: [
        DEPARTMENT_PERMISSIONS.MANAGE_STUDENTS,
        DEPARTMENT_PERMISSIONS.MANAGE_COURSES,
        DEPARTMENT_PERMISSIONS.VIEW_REPORTS
    ],

    STAFF: [
        DEPARTMENT_PERMISSIONS.VIEW_REPORTS
    ]
};
